dev: true
title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
ext:
- go
lang: go
enablerun: true
action:
  before:
  # - go mod tidy
  # - go mod vendor
  - find . -name ".DS_Store" -print -delete
  - gofmt -w ./
  - ps -ef|grep 'mgo_web web'| grep -v grep | awk '{print $2}' | xargs kill -9
  after:
  - ps -ef|grep 'mgo_web web'| grep -v grep | awk '{print $2}' | xargs kill -9
  - ./mgo_web web &
  exit:
  - ps -ef|grep 'mgo_web web'| grep -v grep | awk '{print $2}' | xargs kill -9
  - rm -rf ./mgo_web
link: https://github.com/midoks/zzz
